name: Bug
description: Report a problem or inappropriate behavior
title: "[BUG] "
labels: ["kind:bug", "category:maitenance"]
assignees: []

body:
  - type: textarea
    id: problem
    attributes:
      label: 🐞 Problem Description
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔁 Steps to reproduce the problem
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: 🧪 Evidences
      description: Logs, prints, etc.

  - type: dropdown
    id: severity
    attributes:
      label: ⚠️ Severity
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Acceptance Criteria
      placeholder: |
        - [ ] Bug no longer occurs
        - [ ] Test covers the scenario 
    validations:
      required: true
