name: User Story
description: Functionality from the user’s perspective
title: "[US] "
labels: ["kind:user-story"]
assignees: []

body:
  - type: textarea
    id: story
    attributes:
      label: 👤 History
      description: Standard format
      placeholder: |
        As a [user],
        I want to [action],
        so that [benefit].
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 🧾 Description
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: 🎯 Objective
      description: Business value
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 📂 Category
      options:
        - Feature
        - Improvement
        - Tech Debt
        - Refactor
        - Spike
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: 🧩 Domain
      options:
        - Core
        - Auth
        - Payments
        - Users
        - Notifications
        - Shared
		- Billing
		- Search
		- Admin
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Acceptance Criteria
      placeholder: |
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: tests
    attributes:
      label: 🧪 Test Cases
      placeholder: |
        - [ ] Default Flow
        - [ ] Edge case
        - [ ] Errors

  - type: textarea
    id: dependencies
    attributes:
      label: 🔗 Dependencies

  - type: textarea
    id: references
    attributes:
      label: 📎 References
